apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: node-example
  annotations:
    analysis.scaleops.io/original-metrics: >-
      [{"type":"Resource","resource":{"name":"cpu","target":{"type":"Utilization","averageUtilization":70}}}]
spec:
  minReplicas: 1
  maxReplicas: 4
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dummyDeployment
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 10
